### PR TITLE
GH actions test

### PR DESCRIPTION
**Pull request by wstrange**

### CODE REVIEW

**Comment by wstrange** [comment]
@kevmoo  I simplified the CI to just "dart test" 
Let me know if that works?

Also - should I bump the semver to 1.0.0 - given this is now null safe?

**Comment by kevmoo** [comment]
v1 is Great!

**Comment by wstrange** [comment]
ok - I'll mege your PR,  bump to v1, and then publish 1.0.0

**Comment by wstrange** [comment]
Done!  1.0.0 published


Thanks so much for your help @kevmoo

**Pull request merged**
