### PR TITLE
Bug fixes and tests for PrintableString and UtcTime

### PR DESCRIPTION
**Pull request by jonaskello**

### CODE REVIEW

**Comment by wstrange** [comment]
Hi Jona

Have not had to time to look at this closely -but I think this might not work in all cases.


The asn1 encoding uses a variable length number of bytes to encode the size. If the string is very long, the asn1 encoded length bytes could 2 or 3 bytes. I think your code assumes the length will fit into a byte.

Or am I reading that wrong?

**Comment by jonaskello** [comment]
Yes, I assume one byte for the length. 

I guess this will work for UtcDate since that string cannot be longer than 255? (http://www.obj-sys.com/asn1tutorial/node15.html)

For PrintableString it could be a problem. How do we know how many bytes are  used to specify the length?

**Comment by jonaskello** [comment]
Also I'm not sure if I should really verify that the first byte is the tag since it seems to be possible to override the tag in the constructor?

**Comment by wstrange** [comment]
The call to super() will decode the length bytes for you, and the method "valueBytes()" will return just the value bytes.  

Look at the OctetString:

ASN1OctetString.fromBytes(Uint8List bytes) : super.fromBytes(bytes) {
    octets = valueBytes();
  }

**Comment by wstrange** [comment]
Yes - I don't think you need to verify the tag byte.

If it is being constructed from bytes - you already know what the tag is (you just parsed it).

If you are using the obj constructor the tag can default, or the user can decide to overrride the tag value (needed in some cases - e.g. LDAP)

**Comment by wstrange** [comment]
PrintableString should look pretty much the same as OctectString - just with some extra encoding for ASCII.

**Comment by wstrange** [comment]
For your asn1Utc I think you can also use valueBytes()

You should not need bytes.sublist....

I should make the doc more clear - but the super() call does the first bit of length decoding for you

**Comment by jonaskello** [comment]
Ok I will fix that on my branch which I think will add another commit to the PR? Let you know when it is in.

**Comment by wstrange** [comment]
Err - Im a github  newbie

Is it easier just to submit a new pull request? And I will just close this one?

I did just make a previous commit - to the master.

**Comment by jonaskello** [comment]
Hehe, so we are two newbies :-). I read somewhere that the PR would be updated automatically if I commit to the branch it is based on. I think I can try to add a commit and we'll see if the diff looks OK and if there are no conflicts? Almost done...

**Comment by jonaskello** [comment]
Second commit is in now. Seems like the PR updated automatically :-). You should be able to see the diff including the second commit now...

**Pull request merged**
