### PR TITLE
PEM PKCS#8 private key unit test

### PR DESCRIPTION
**Pull request by areiter**
Just in case someone else needs it, I added the extraction of parameters for a PKCS#8 encoded private key.

### CODE REVIEW

**Comment by stevenroose** [comment]
Personally, I'd make the `contentBytes()` function a getter instead of a function.

But otherwise, good PR! Always nice to have extra tests! :)

**Comment by areiter** [comment]
I used a _method_ because _valueBytes()_ is also a method. But a getter seems to be a cleaner approach :-)

**Comment by stevenroose** [comment]
On the other hand, a getter would be inconsistent with the already existing `valueBytes()`. So I guess this is fine. 

I'll take a second look and run the tests when I'm on my computer. Thanks for the PR!

**Comment by stevenroose** [comment]
Hah, you got me there. 

Well, if we change both, we break compatibility, so that's maybe something for if we would change the whole interface. Nothing for the foreseeable future. So leave it as a method, it's fine.

**Comment by stevenroose** [comment]
Uhm, just wanted to merge this, but you seem to have pushed another change onto the branch. Can you set the branch one commit back and create a new PR for the other change?

(Also, it seems to me you forgot the `encodeInteger` method in that new commit.)

**Comment by areiter** [comment]
Sorry, follow-up #19

**Pull request closed without merging**
