### PR TITLE
Add support for PrintableString and UtcDate (with tests)

### LINKED ISSUE #12: Support for RSA PEM Public Key, specifically tag 19 PrintableString
I'm trying to parse a PEM encoded RSA public key. I'm hitting an exception "Parser for tag 19 not implemented yet". I think the problem is that the PEM encoding actually has a tag 19 which from what I gather from http://www.obj-sys.com/asn1tutorial/node124.html is a "PrintableString".

I also used this tool to verify my PEM ecoded public key:

https://holtstrom.com/michael/tools/asn1decoder.php

Below follow the full PEM encoding I use to test (it is from a self-signed example cert). I think adding support for tag 19 should not be to hard. Maybe I can fork and make a pull request?

MIIDBTCCAfGgAwIBAgIQNQb+T2ncIrNA6cKvUA1GWTAJBgUrDgMCHQUAMBIxEDAOBgNVBAMTB0RldlJvb3QwHhcNMTAwMTIwMjIwMDAwWhcNMjAwMTIwMjIwMDAwWjAVMRMwEQYDVQQDEwppZHNydjN0ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqnTksBdxOiOlsmRNd+mMS2M3o1IDpK4uAr0T4/YqO3zYHAGAWTwsq4ms+NWynqY5HaB4EThNxuq2GWC5JKpO1YirOrwS97B5x9LJyHXPsdJcSikEI9BxOkl6WLQ0UzPxHdYTLpR4/O+0ILAlXw8NU4+jB4AP8Sn9YGYJ5w0fLw5YmWioXeWvocz1wHrZdJPxS8XnqHXwMUozVzQj+x6daOv5FmrHU1r9/bbp0a1GLv4BbTtSh4kMyz1hXylho0EvPg5p9YIKStbNAW9eNWvv5R8HN7PPei21AsUqxekK0oW9jnEdHewckToX7x5zULWKwwZIksll0XnVczVgy7fCFwIDAQABo1wwWjATBgNVHSUEDDAKBggrBgEFBQcDATBDBgNVHQEEPDA6gBDSFgDaV+Q2d2191r6A38tBoRQwEjEQMA4GA1UEAxMHRGV2Um9vdIIQLFk7exPNg41NRNaeNu0I9jAJBgUrDgMCHQUAA4IBAQBUnMSZxY5xosMEW6Mz4WEAjNoNv2QvqNmk23RMZGMgr516ROeWS5D3RlTNyU8FkstNCC4maDM3E0Bi4bbzW3AwrpbluqtcyMN3Pivqdxx+zKWKiORJqqLIvN8CT1fVPxxXb/e9GOdaR8eXSmB0PgNUhM4IjgNkwBbvWC9F/lzvwjlQgciR7d4GfXPYsE1vf8tmdQaY8/PtdAkExmbrb9MihdggSoGXlELrPA91Yce+fiRcKY3rQlNWVd4DOoJ/cPXsXwry8pWjNCo5JD8Q+RQ5yZEy7YPoifwemLhTdsBz3hlZr28oCGJ3kbnpW0xGvQb3VHSTVVbeei0CfXoW6iz1

### PR DESCRIPTION
**Pull request by jonaskello**
This fixes #12

### CODE REVIEW

**Comment by stevenroose** [comment]
Are you sure that the UTF-16 encoding works correctly? I read that `PrintableString` f.e. uses ASCII.

**Comment by jonaskello** [comment]
Yes, I should probably add some more tests to test that the PrintableString encoding works properly. I'll do that in a new branch then?

**Comment by wstrange** [comment]
That would be great. I assume you will send a new pull request?

Once I get that I will bump the version number and push it to pub

**Comment by jonaskello** [comment]
I'll send a new PR, hopefully later today.

**Comment by jonaskello** [comment]
I'm a bit uncertain how to implement _encode() for ASN1PrintableString. When fromBytes() get called by the main parser the first byte is the tag (19) and the second byte is the length of the string. Should I include that as the first two byes from _encode() so it produces the same bytes as fromBytes() gets called with? Or should I skip those two bytes and only set the actual string content bytes in _encode()?

**Comment by jonaskello** [comment]
Ah, found the answer, _encodeHeader() does the first two bytes so no need to do them.

**Comment by stevenroose** [comment]
Best you can do is look at the `_encode` implementations of the other classes. That's how I figured it out the first time :)

**Pull request merged**
