### PR TITLE
Add support for BMPString

### PR DESCRIPTION
**Pull request by declanwoods**
Hi, I recently needed support for BMPString, so I have added it. Please let me know if you need anything to change.

### CODE REVIEW

**Comment by wstrange** [comment]
This looks great - Thanks Declan!

Can you bump the version in pubspec to 1.0.3 and add a changelog.md entry. After that I'll merge and push a new version to pub.

**Comment by declanwoods** [comment]
Done @wstrange ​:)​

**Comment by wstrange** [comment]
Almost there! Can you run dartfmt.  The PR check is failing on:
Changed lib/asn1bmpstring.dart
Changed lib/asn1parser.dart

**Comment by wstrange** [comment]
Thanks Declan - much appreciated!

I pushed the new package to pub.dev

**Pull request merged**
