### PR TITLE
Add ASN1IpAddress object to better support SNMP applications

### PR DESCRIPTION
**Pull request by point-source**
Note that since this is an SNMP-specific feature, I have not added the ASN1pAddress object to the parser since tag 0x40 may not always mean IP_ADDRESS in all cases. Still, having this object available in the library extends the useability of this library in SNMP applications.

### CODE REVIEW

**Review by wstrange — APPROVED** [review]
Looks great - should we bump to 0.8.1?

**Comment by point-source** [comment]
Happy to bump to whatever you like, not sure what the .1 is to signify here though since I already moved from 0.7.0 to 0.8.0 with this PR. Unless you are referring to the combination of this PR and my other one.

**Comment by wstrange** [comment]
> Happy to bump to whatever you like, not sure what the .1 is to signify here though since I already moved from 0.7.0 to 0.8.0 with this PR. Unless you are referring to the combination of this PR and my other one.

Yea - I got a bit confused here. Do you want this PR to go in first?

If so - then the next PR should probably be 0.8.1 to signal a possible (non breaking) change in behavior?

**Comment by point-source** [comment]
I had originally assumed the bug fix would go in first mostly because new features usually take more review / testing but since you're good with both, I happy to go in any order you want. I actually have another one coming with a fix for oids that have a zero-octet. If you would prefer me to merge these together, I can. I've just had maintainers in the last ask me to keep them separate so they can choose what goes/what doesn't. But doing it that way puts the burden of updating the version on the maintainer.

**Comment by wstrange** [comment]
OK - first PR merged!

**Comment by point-source** [comment]
Conflicts resolved

**Comment by wstrange** [comment]
Merged - and thanks so much for your help!

I'll push the new version to pub ASAP

**Comment by point-source** [comment]
Haha no problem! Happy to help. I got one more PR coming, can push after that haha.

**Pull request merged**
