### PR TITLE
 fix: use `valueBytes()[0]` for `ASN1BitString.fromBytes`

### PR DESCRIPTION
**Pull request by skyler-lb**
Also adds a (couple) regression test(s).

### CODE REVIEW

**Comment by wstrange** [comment]
Thanks for the PR Skyler. Can you add a changelog.md entry, and bump the minor semver in pubspec. Then I will push a new  version to pub.dev

**Comment by skyler-lb** [comment]
To be clear, you expressly want me to bump the version to `1.2.0`? (major 1, minor 1, patch 0 -> 1.2.0)

**Comment by wstrange** [comment]
I kinda think this is a minor patch?    So 1.1.1

Thanks

**Comment by wstrange** [comment]
Thanks for the PR - much appreciated!

**Pull request merged**
